Default: &defaults
  database: vicky3-Projekt.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: vicky3-Projekt_test.sqlite3
  <<: *defaults

Staging:
  database: vicky3-Projekt_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: vicky3-Projekt_production.sqlite3
  poolsize: 100
  <<: *defaults
